### ISSUE TITLE
Unused dependencies

### ISSUE THREAD

**Issue by SuperITMan** [Trust1Team/t1c-lib-js#11]
Hello, 

After trying your version 2.2.0, I saw you have at least one unused/useless dependency which is installed with your library when we install it. -> `"npm": "^6.1.0`
There is also `path` which is normally included with node directly. I think you can also remove this dependency. 

Finally, I think a cleanup of your dependencies could be necessary and in the same time you could update some of them.

Thanks.
Alexis GEORGES

**Comment by michallis** [comment]
Thank you for the feedback Alexis, will pick that up together with your remarks. 
regards, 
Michallis
