### ISSUE TITLE
Import lib by webpack 4 and angular 5 project

### ISSUE THREAD

**Issue by KrakenTyio** [Trust1Team/t1c-lib-js#3]
Hi,

We have huge Angular project, bundled by webpack 4.

I install your lib on version 2.1.6 by
```bash
npm i trust1connector
```

we have this code
```ts
import { CardReadersResponse, GCLClient, GCLConfig, GCLConfigOptions } from 'trust1connector';

....
getEid() {
        const options = new GCLConfigOptions();
        options.apiKey = globals.trust1Key;
        options.gwOrProxyUrl = 'https://apim.t1t.be:443';

        const gclConfig = new GCLConfig(options);

        return Observable.fromPromise(GCLClient.initialize(gclConfig))
            .flatMap((client: GCLClient) => {
                return Observable.fromPromise(client.core().readersCardAvailable())
                    .flatMap((readers: CardReadersResponse) => {
                        if (readers.data.length) {
                            return Observable.fromPromise(client.beid(readers.data[0].id).allData({
                                filters: ['rn', 'address', 'picture'],
                                parseCerts: false
                            }));
                        }
                        return Observable.throw('No readers');
                    });
            }).subscribe();
}
```

But on load module we get error like this
```console
Uncaught TypeError: trust1connector_1.GCLConfigOptions is not a constructor
```

When i try load just lib
```ts
GCLClient.initialize({});
```

we get this error
```console
Uncaught TypeError: Cannot read property 'initialize' of undefined
```

**Comment by michallis** [comment]
Hi, 

Did you have a look at:
https://github.com/Trust1Team/readmycards-webapp-ng

and the online documentation:
https://t1t.gitbook.io/t1c-js-guide-v2/

In the example repo - which is deloyed at: https://rmc.t1t.be/ = you see:
    const service = this;
    service.connector = this.GCLLib.GCLClient.initialize(gclConfig).then(client => {
      service.connector = client;
      return Promise.resolve(service.connector);
    }, err => {
      service.connector = err.client;
      return Promise.reject(err);
    });
    return service.connector;

ref: https://github.com/Trust1Team/readmycards-webapp-ng/blob/master/src/app/connector.service.ts


Does this help you?
Do you need a test apikey ? 

best regards

**Comment by ncedric** [comment]
I have the exact same behaviour.
Same code, same version of webpack and angular.

I have tried multiples multipes ways of importing but GCLOptions GLCOptionsConfig cannot be instantiated using constructor ( classes imported from trust1connector are undefinned)

**Comment by michallis** [comment]
Hi, 

Can you have a look at the example implementation:
https://github.com/Trust1Team/readmycards-webapp-ng/blob/master/src/app/connector.service.ts

maybe this can help you, and we use it as reference implementation. 
In mean time I'm looking to simulate the issue (as we don't have it in our demo applications) in order to fix this. 

@KrakenTyio it's not possible to call initialize without the GCLConfig, it's a required parameter

**Comment by michallis** [comment]
@KrakenTyio additional info, avoid for the moment the GCLConfigOptions object, and try to directly:
new this.GCLLib.GCLConfig({
        gwJwt: res.token,
        gwOrProxyUrl: environment.gwOrProxyUrl,
        gclUrl: environment.gclUrl,
        ocvContextPath: environment.ocvContextPath,
        implicitDownload: environment.implicitDownload,
        agentPort,
        osPinDialog: environment.osPinDialog,
        pkcs11Config: pkcs11
      });
    });

this will unblock you at the moment

**Comment by michallis** [comment]
The reason why it goes wrong is as following:
The GCLLib has a Polyfills check in the v2, this is to NOT override polyfills in the application context. So this means you need to:
- Angular 2.x: add to the .angular-cli.json > in scripts section: 
      "scripts": [
        "../node_modules/trust1connector/dist/GCLLib.js"
      ],

For people coming from T1C v1 you can follow the migration guide:
https://t1t.gitbook.io/t1c-js-guide-v2/core/migration-guide-v1-greater-than-v2

And the best reference code is:
https://github.com/Trust1Team/readmycards-webapp-ng/blob/master/src/app/connector.service.ts

You'll notice we load the GCLLib by:
private GCLLib = window['GCLLib'];

And guarantee the polyfill check is executed.

I hope this works for you both. 

Let me know if ok

**Comment by KrakenTyio** [comment]
We have lazy loaded modules, so we cannot bind direct to global scope.
But we avoid config and load direct from js object to gclib and its work.

**Comment by KrakenTyio** [comment]
Hi we return back to resolve implementation of your lib and find solution as bellow:

```ts
import { CardReadersResponse, GCLClient, GCLConfig } from 'trust1connector';

export class EdiService {
   GCLLib: { GCLClient: Type<GCLClient>, GCLConfig: Type<GCLConfig> } = require('exports-loader?GCLLib!trust1connector');

   get(): Observable<{}> {
        const gclConfig = new this.GCLLib.GCLConfig({
            gwJwt: ''
        });

       return from((this.GCLLib.GCLClient as any).initialize(gclConfig))
            .pipe(
                flatMap((client: GCLClient) => {
                    ....
                })
            );
   }
}
```

for webpack 4 `exports-loader` do hard work and load your lib when needed.
