### ISSUE TITLE
Regression in GCLConfig

### ISSUE THREAD

**Issue by SuperITMan** [Trust1Team/t1c-lib-js#5]
Hello,

Previously (version 2.1.7), there was a class GCLConfigOptions which allowed to pass typed object throught GCLConfig constructor which was really useful.

Since version 2.1.8, GCLConfigOptions class has been removed and the signature of the constructor of GCLConfig is now *constructor(options: any)*. 

It was a bit better before because we had the auto-completion and the validation of the object itself, even if the class forced all properties as required instead of optional (which was annoying because that forced us to cast the object as "any").

Could you please add back the GCLConfigOptions class and improve this a bit by making optional properties optional. 

Thank you.
Alexis GEORGES

**Comment by michallis** [comment]
Hi, 

we'll add this again, in the previous version this cause still the 'not a constructor' issue due to the way of initializing the library. 

regards, 
Michallis
