### ISSUE TITLE
GCL Mac Installer

### ISSUE THREAD

**Issue by qlecler** [Trust1Team/t1c-lib-js#64]
Hi there,

Where could I find the Mac OS installer for GCL ?

Thanks 👍

**Comment by michallis** [comment]
Hi, 

For v2 you can find it here:
https://storage.googleapis.com/gcl-distro/v2.0.0/Trust1Connector.dmg

But using the example application:
https://readmycards.eu/

The download will automatically detect OSX

best regards, 
Michallis

**Comment by qlecler** [comment]
Thanks 👍 

v1 example doesn't seems to work anymore.

Do you have a working example for v2 ?

**Comment by qlecler** [comment]
Hello,

Do you have the link (v2)  for Windows ?

Thanks 👍

**Comment by jonasvekeman** [comment]
Hi

If you enter your mail address at https://readmycards.eu on a Windows machine, you'll receive the download link.

Direct links: 
- https://storage.googleapis.com/gcl-distro/v2.0.0/Trust1Connector_x64.msi
- https://storage.googleapis.com/gcl-distro/v2.0.0/Trust1Connector_x86.msi

Code samples and documentation can be found at https://t1t.gitbook.io/t1c-js-guide-v2/. Please keep in mind you'll need a valid API key if you want to develop your own application.

**Comment by qlecler** [comment]
Hi,

Thanks 👍
