### ISSUE TITLE
CORS issue with HTTPS

### ISSUE THREAD

**Issue by qlecler** [Trust1Team/t1c-lib-js#78]
Hey there !

I've issues trying to communicate with the middleware in HTTPS.

With plain HTTP in localhost it doesn't work obviously :

`Access to XMLHttpRequest at 'https://localhost:10443/v2/containers/beid-v2-0-0/30a5af2d6c7b77ef' from origin 'http://xxx:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

In HTTPS (with valid certificate) on the test end we still have this error :

`Access to XMLHttpRequest at 'https://localhost:10443/v2/containers/beid-v2-0-0/30a5af2d6c7b77ef' from origin 'https://xxx:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by jonasvekeman** [comment]
Hi

Do you have an active API key for the Trust1Connector? The CORS whitelist is linked to this API key and configured in our backend.

Kind regards,
Jonas

**Comment by qlecler** [comment]
No, for now we're only testing the product with the api key provided in the examples.

Just trying to make it work in HTTPS.

We're currently working on a large app and reviewing all the libraries that works with EID.

**Comment by jonasvekeman** [comment]
It's better to have a separate API key for your organisation, those test API keys might expire/be removed.

If you could contact me at jonas@trust1team.com with some additional information, I will provide you with an API key for our acceptance environment:

- Company
- Required CORS whitelist

We can provide you with the pricing information as well if you decide to go into production with the Trust1Connector. You'll need a separate API key for this as well.

Kind regards,
Jonas
